---
prometheus_web_external_url: "https://p.monitor.izv.ee"
prometheus_storage_retention: "180d"

prometheus_global:
  scrape_interval: 10s
  scrape_timeout: 9s
  evaluation_interval: 15s

prometheus_alertmanager_config:
  - scheme: http
    static_configs:
      - targets:
          - "127.0.0.1:9093"

prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: izv_node
    static_configs:
      - targets: ['izv.ee:9100']
  - job_name: izv_mysql
    static_configs:
      - targets: ['izv.ee:9104']
  - job_name: tile_node
    static_configs:
      - targets: ['tile.osmz.ru:9100']
  - job_name: tile_psql
    static_configs:
      - targets: ['tile.osmz.ru:9187']
